// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/demo_repo.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/demo_repo.go -destination=test/mocks/repository/demo_repo.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	model "go_template/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDemoRepository is a mock of DemoRepository interface.
type MockDemoRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDemoRepositoryMockRecorder
	isgomock struct{}
}

// MockDemoRepositoryMockRecorder is the mock recorder for MockDemoRepository.
type MockDemoRepositoryMockRecorder struct {
	mock *MockDemoRepository
}

// NewMockDemoRepository creates a new mock instance.
func NewMockDemoRepository(ctrl *gomock.Controller) *MockDemoRepository {
	mock := &MockDemoRepository{ctrl: ctrl}
	mock.recorder = &MockDemoRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDemoRepository) EXPECT() *MockDemoRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockDemoRepository) Delete(ctx context.Context, parkCode int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, parkCode)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDemoRepositoryMockRecorder) Delete(ctx, parkCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDemoRepository)(nil).Delete), ctx, parkCode)
}

// GetByParkCode mocks base method.
func (m *MockDemoRepository) GetByParkCode(ctx context.Context, parkCode int64) ([]model.Demo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByParkCode", ctx, parkCode)
	ret0, _ := ret[0].([]model.Demo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByParkCode indicates an expected call of GetByParkCode.
func (mr *MockDemoRepositoryMockRecorder) GetByParkCode(ctx, parkCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByParkCode", reflect.TypeOf((*MockDemoRepository)(nil).GetByParkCode), ctx, parkCode)
}
