version: "2"
run:
  timeout: 5m
  concurrency: 4
  tests: false

linters:
  enable:
    - govet
    - errcheck       # 检查未处理 error
    - staticcheck    # 超全面语义/潜在bug检查
    - gosec          # 安全漏洞检查
    - ineffassign    # 无效赋值
    - unused         # 未使用变量/函数/常量
    - unparam        # 未使用参数
    - gocyclo        # 函数复杂度检查

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
