name: go_template
mode: debug
port: 8073
read_timeout: 5
shutdown_timeout: 5

log:
  level: debug
  filename: go_template.log
  max_size: 1024
  max_age: 7
  max_backups: 3
  compress: false
  encoding: json
  mode: console

db:
  dsn: root:maogou919@tcp(127.0.0.1:3306)/demo?charset=utf8mb4&parseTime=True&loc=Local
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 300

redis:
  addr: 127.0.0.1:6379
  password:
  db: 3
  lock_timeout: 86400
