// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/demo_service.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/demo_service.go -destination=test/mocks/service/demo_service.go
//

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	v1 "go_template/api/v1"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDemoService is a mock of DemoService interface.
type MockDemoService struct {
	ctrl     *gomock.Controller
	recorder *MockDemoServiceMockRecorder
	isgomock struct{}
}

// MockDemoServiceMockRecorder is the mock recorder for MockDemoService.
type MockDemoServiceMockRecorder struct {
	mock *MockDemoService
}

// NewMockDemoService creates a new mock instance.
func NewMockDemoService(ctrl *gomock.Controller) *MockDemoService {
	mock := &MockDemoService{ctrl: ctrl}
	mock.recorder = &MockDemoServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDemoService) EXPECT() *MockDemoServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDemoService) Create(ctx context.Context, req *v1.AddAuthRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDemoServiceMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDemoService)(nil).Create), ctx, req)
}

// GetDemo mocks base method.
func (m *MockDemoService) GetDemo(ctx context.Context, parkCode int64) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDemo", ctx, parkCode)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDemo indicates an expected call of GetDemo.
func (mr *MockDemoServiceMockRecorder) GetDemo(ctx, parkCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDemo", reflect.TypeOf((*MockDemoService)(nil).GetDemo), ctx, parkCode)
}
